### ISSUE TITLE
Allow disabling the world locks

### ISSUE THREAD

**Issue by Madis0** [Modpack-Update-Checker/RoadmapPublic#18]
I do not want this feature and I haven't figured out if there is a way to disable it for my modpack
![img](https://github.com/Modpack-Update-Checker/RoadmapPublic/assets/8611110/9758e30d-a642-4fb1-82ae-07547af9cac5)
![img](https://github.com/Modpack-Update-Checker/RoadmapPublic/assets/8611110/cc667a2e-7ce3-4047-a327-033cc182a2df)

Edit: I figured out it refers to this:

> A new advanced field retroWarning allows you to configure whether a warning screen is shown when opening worlds that have no associated MPUC metadata.

I have it set to false but it is still shown, so it seems to be a bug.

**Comment by Jab125** [comment]
There is a hidden advanced field called `forceModpackCompatible`, you'll still get the warning screen, but should still be able to join regardless.

**Comment by Madis0** [comment]
Okay, but I'd like to disable all aspects of it, so that the mod would not touch my worlds at all.

**Comment by Jab125** [comment]
In that case, open a new issue that states that.
