### ISSUE TITLE
Misaligned button

### ISSUE THREAD

**Issue by Madis0** [Modpack-Update-Checker/RoadmapPublic#19]
Using MUC 0.12.0 for Minecraft 1.20.4
The only other mod I have that injects to main menu buttons is Mod Menu. Tried disabling that and Main Menu Credits, still same result. Also tried toggling `expandButton`.
![img](https://github.com/Modpack-Update-Checker/RoadmapPublic/assets/8611110/f66c9eee-a627-4c7a-8733-9412aff01a29)

**Comment by Jab125** [comment]
You can re-align the button `buttonXOffset` and `buttonYOffset` in the `advanced` section of the Modpack Update Checker config.
